#!/bin/bash
#
#See skript on kontrollimiseks kas apache on installitud

APACHE2=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c "ok installed")
#Kontrollib kas apache on juba paigaldatud
if [ $APACHE2 -eq 0 ]; then #kui väärtus on 0 siis alustab apachet paigaldusega
	echo "Apachet paigaldatakse"
	apt-get install -y apache2 #paigaldamise käsk
elif [ $APACHE2 -eq 1 ]; then #kui väärtus on 1 siis ütleb et apache on paigaldatud
	echo "Apache2 on installitud"
	service apache2 status #näitab apache olekut
fi

