#!/bin/bash
php=$(dpkg-query -W -f='${Status}' php7.3 2>/dev/null | grep -c "ok installed")
if [ $php -eq 0 ]; then
	echo "PHP paigaldamine"
	apt-get install -y ca-certificates apt-transport-https lsb-release
	wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
	echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php7.3.list
	#võtab internetist võtmed ja installib sertifikaadid
	apt-get update #installib uuendused
	apt-get install -y php7.3 php7.3-cli php7.3-common php7.3-opcache php7.3-curl php7.3-mbstring php7.3-mysql php7.3-zip php7.3-xml
elif [ $php -eq 1 ]; then
	echo "php paigaldatud"
fi
